apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-deployment
  labels:
    app: fibonacci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
      annotations:
        prometheus.io/scrape: "true"  # Разрешить Prometheus собирать метрики
        prometheus.io/port: "8000"    # Указать порт для метрик
    spec:
      containers:
        - name: fibonacci
          image: birthtree/fibonacci:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"