apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "fibonacci-chart.fullname" . }}
  labels:
    {{- include "fibonacci-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fibonacci-chart.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: External
      external:
        metric:
          name: fibonacci_requests_total  
          selector:
            matchLabels:
              job: fibonacci-service  
        target:
          type: Value
          value: "1000"  
