apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  labels:
    app: fibonacci 
spec:
  selector:
    app: fibonacci  
  ports:
    - name: "8080" 
      protocol: TCP
      port: 8080    
      targetPort: 8080  
  type: ClusterIP