# Default values for fibonacci-chart.

replicaCount: 2

image:
  repository: birthtree/fibonacci
  pullPolicy: Always
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080  # Порт для сервиса




ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http  # Используем имя порта, который зададим в контейнере
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 10



readinessProbe:
  httpGet:
    path: /
    port: http  # Используем имя порта
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80


volumes: []
volumeMounts: []

prometheus:
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    endpoints:
      - port: 8080  # Для ServiceMonitor можно оставить числом
        path: "/metrics"

nodeSelector: {}

tolerations: []

affinity: {}
