name: CI/CD Pipeline

on:
  push:
    branches:
      - lab3

jobs:
  RunMake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential g++ cmake git libcurl4-openssl-dev

      - name: Install Prometheus C++ Client
        run: |
          git clone --recursive https://github.com/jupp0r/prometheus-cpp.git
          cd prometheus-cpp
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_BENCHMARK=OFF -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          sudo make install
          sudo ldconfig  # Обновляем кэш ldconfig

      - name: Verify Prometheus C++ Client Installation
        run: |
          find /usr/lib -name "libprometheus-cpp*" || echo "Library not found!"
          ldconfig -p | grep prometheus-cpp || echo "Library not found in ldconfig!"

      - name: Build Project
        run: |
          cd src
          make || { echo "Make failed"; exit 1; }
          mkdir -p ../artifacts  # Создаем папку для артефактов
          cp fibonacci ../artifacts/  # Копируем бинарный файл в папку artifacts
          ls -l ../artifacts  # Проверяем, что файл скопирован
          mkdir -p ../usr/bin
          cp fibonacci ../usr/bin/  # Копируем бинарный файл в папку usr/bin
          rm -f fibonacci  # Удаляем файл после копирования

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fibonacci-binary
          path: artifacts/fibonacci  # Указываем путь к файлу в папке artifacts

  RunPackage:
    needs: RunMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Binary Artifact
        uses: actions/download-artifact@v4
        with:
          name: fibonacci-binary
          path: artifacts/

      - name: Create Debian Package
        run: |
          mkdir -p artifacts/deb/usr/local/bin
          mkdir -p artifacts/deb/DEBIAN
          cp DEBIAN/control artifacts/deb/DEBIAN/
          cp artifacts/fibonacci artifacts/deb/usr/local/bin/
          dpkg-deb --build artifacts/deb fibonacci.deb

      - name: Upload Debian Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fibonacci-deb
          path: fibonacci.deb

  RunDeploy:
    needs: RunPackage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Debian Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: fibonacci-deb
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: birthtree/fibonacci:latest

      - name: Restart Kubernetes Deployment
        run: |
          kubectl rollout restart deployment fibonacci-deployment