name: CI Pipeline

on:
  push:
    branches:
      - lab2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential dpkg

      - name: Run Make
        run: |
          cd src
          g++ -Wall -Wextra -O2 Fibi.cpp -o fibonacci || { echo "Compilation failed"; exit 1; }
          ls -l  # Проверяем, что файл fibonacci существует в папке usr/bin
          mkdir -p ../artifacts
          cp ../usr/bin/fibonacci ../artifacts/ || { echo "Failed to copy fibonacci"; exit 1; }

      - name: Upload Artifact (Binary)
        uses: actions/upload-artifact@v4
        with:
          name: fibonacci-binary
          path: artifacts/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: fibonacci-binary
          path: artifacts/

      - name: Run Tests
        run: |
          chmod +x artifacts/fibonacci
          ./artifacts/fibonacci 10 | grep "Number of Fibonacchi #10 = 55"
          ./artifacts/fibonacci 1 | grep "Number of Fibonacchi #1 = 1"
          ./artifacts/fibonacci 99 | grep "Number of Fibonacchi #99 = 218922995834555169026"

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: fibonacci-binary
          path: artifacts/

      - name: Create Debian Package
        run: |
          mkdir -p artifacts/deb/usr/local/bin
          cp artifacts/fibonacci artifacts/deb/usr/local/bin/
          dpkg-deb --build artifacts/deb fibonacci.deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: fibonacci-deb
          path: fibonacci.deb
